CREATE TABLE IF NOT EXISTS Team(
Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Name VARCHAR(45));

ALTER TABLE User
ADD COLUMN Team INT NOT NULL;


CREATE INDEX user_team_idx ON Team (Id);

ALTER TABLE User
ADD CONSTRAINT fk_Team_Id FOREIGN KEY (Team) REFERENCES Team (Id);